language: r
cache: packages
sudo: false

script:
  - Rscript -e "rmarkdown::render_site(encoding = 'UTF-8')"

after_success:

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: docs
  on: 
    branch: master


