language: r
cache: packages
sudo: false

script:
  - Rscript -e 'devtools::check()'

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: docs
  on: 
    branch: master


